baseurl                  = "https://example.com/"           # Your domain name. Must end with "/"
languageCode             = "de"
defaultContentLanguage   = "de"
isMultilingual           = false
title                    = "Julius Schmitt"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006"
    dateformfull         = "2006"
    favicon              = "punkt.png"
    homepage             = "main"                           # What to call the home page link
    footerText           = "[Impressum](/Impressum)"

# Metadata for Open Graph and Twitter
    description          = "Julius Schmitt - Filmemacher"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Julius Schmitt"

[[params.mainMenu]]
    link = "/posts"
    text = "Hallo"

[[params.mainMenu]]
    link = "/gallery"
    text = "Ich bin Julius"

[[params.mainMenu]]
    link = "/portfolio"
    text = "Filmemacher"

[[params.mainMenu]]
    link = "/about"
    text = "und 33,3% von Carlo"

[imaging]
    quality = 75
